[default]
depends = ["emacs", "fcitx", "git", "kitty"]

[emacs.files]
"packages/emacs/init.el" = "~/.config/emacs/init.el"
"packages/emacs/custom.el" = "~/.config/emacs/custom.el"
"packages/emacs/zeromini-theme.el" = "~/.config/emacs/zeromini-theme.el"

[fcitx.files]
# Force all of these to be templates, fcitx5 overrides these by default.
"packages/fcitx/config" = { target = "~/.config/fcitx5/config", type = "template" }
"packages/fcitx/keyboard.conf" = { target = "~/.config/fcitx5/conf/keyboard.conf", type = "template" }
"packages/fcitx/quickphrase.conf" = { target = "~/.config/fcitx5/conf/quickphrase.conf", type = "template" }
"packages/fcitx/QuickPhrase.mb" = { target = "~/.local/share/fcitx5/data/QuickPhrase.mb", type = "template" }

[git.files]
"packages/git/git-sync.timer" = "~/.config/systemd/user/git-sync.timer"
"packages/git/git-sync.service" = "~/.config/systemd/user/git-sync.service"
"packages/git/git-sync-all.sh" = "~/.local/share/git/git-sync-all.sh"

[git.variables]
git_includes = []
git_gpg = false
git_lfs = false
git_sync = []

[kitty.files]
"packages/kitty/tab_bar.py" = "~/.config/kitty/tab_bar.py"
"packages/kitty/server-imgs" = { target = "~/.config/kitty/server-imgs", type = "symbolic" }
"packages/kitty/launch-kitty" = "~/.local/bin/launch-kitty"

[tmux.files]
"packages/tmux/tmux.conf" = "~/.config/tmux/tmux.conf"
"packages/tmux/tmux-24bit.terminfo" = "~/.config/tmux/tmux-24bit.terminfo"
